import { InitOptions } from "i18next";

export const translate: InitOptions = {
  resources: {
    en: {
      translation: {
        home: "Home",
        search: "Search",
        hero: "A service that helps you share your messages",
        herobtn: "try it",
        create: "Create your message",
        createAuthor: "Author",
        createMessage: "Message",
        createPassword: "Password",
        createShowPass: "Show password",
        createMaxViews: "Max views",
        createEdit: "Can other edit message?",
        createbtn: "Create message",
        code: "Your code to message ",
        close: "Close",
        loading: "Loading",
        view: "View",
        pageisntexist: "This page don't exist",
        passwordToMessage: "Password to message:",
        messageAuthor: "Author: ",
        messageEdit: "edit",
        messageSave: "save",
        messageViews: "Views: ",
        messageMaxViews: "Max views: ",
        messageDate: "Date: ",
        messageNewMessage: "New message",
      },
    },
    ru: {
      translation: {
        home: "Главная",
        search: "Поиск",
        hero: "Сервис которий помогает вам делиться своими сообщениями",
        herobtn: "попробовать",
        create: "Создайте свое сообщение",
        createAuthor: "Автор",
        createMessage: "Сообщение",
        createPassword: "Пароль",
        createShowPass: "Показать пароль",
        createMaxViews: "Максимальное количество просмотров",
        createEdit: "Могут ли другие редактировать сообщение?",
        createbtn: "Создать сообщение",
        code: "Ваш код для сообщения",
        close: "Закрыть",
        loading: "Загрузка",
        view: "Посмотреть",
        pageisntexist: "Этой страницы не существует",
        passwordToMessage: "Пароль к сообщению:",
        messageAuthor: "Автор: ",
        messageEdit: "Редактрировать",
        messageSave: "Сохранить",
        messageViews: "Просмотров: ",
        messageMaxViews: "Максимум просмотров: ",
        messageDate: "Дата: ",
        messageNewMessage: "Новое сообщение",
      },
    },
    ua: {
      translation: {
        home: "Головна",
        search: "Пошук",
        hero: "Сервіс, який допомагає вам ділитися своїми повідомленнями",
        herobtn: "Спробувать",
        create: "Створіть своє повідомлення",
        createAuthor: "Автор",
        createMessage: "Повідомлення",
        createPassword: "Пароль",
        createShowPass: "Показать пароль",
        createMaxViews: "Максимальна кількість переглядів",
        createEdit: "Чи можуть інші редагувати повідомлення?",
        createbtn: "Створити повідомлення",
        code: "Ваш код для повідомлення",
        close: "Закрити",
        loading: "Завантаження",
        view: "Подивитися",
        pageisntexist: "Цієї сторінки не існує",
        passwordToMessage: "Пароль до повідомлення:",
        messageAuthor: "Автор: ",
        messageEdit: "редагувати",
        messageSave: "зберегти",
        messageViews: "Перегляди: ",
        messageMaxViews: "Максимум переглядів:",
        messageDate: "Дата: ",
        messageNewMessage: "Нове повідомлення",
      },
    },
  },
  lng: localStorage.getItem("language") || "en",
};
